//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIANTE
    {
        public long ID_ESTUDIANTE { get; set; }
        public long ID_TIPO_DOC { get; set; }
        public string NUMERO_IDENTIFICACION { get; set; }
        public string PRIMER_NOMBRE { get; set; }
        public string SEGUNDO_NOMBRE { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public Nullable<long> ID_GENERO { get; set; }
        public string CELULAR { get; set; }
    
        public virtual GENERO GENERO { get; set; }
        public virtual TIPO_DOC TIPO_DOC { get; set; }
    }
}
