//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArquitecturaSoftwareEntities : DbContext
    {
        public ArquitecturaSoftwareEntities()
            : base("name=ArquitecturaSoftwareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ESTUDIANTE> ESTUDIANTEs { get; set; }
        public virtual DbSet<GENERO> GENEROes { get; set; }
        public virtual DbSet<TIPO_DOC> TIPO_DOC { get; set; }
    }
}
